---
title: "Survival Models and Data Vis"
output: html_notebook
---



```{r}
library(survival)
library(ggsurvfit)
library(tidyverse)
library(tidymodels)
library(ggcorrplot)
library(ggplot2)
library(censored)

```

#PFS model
#Make stat code and time variables numeric.

```{r}
MCL_cox_pfs$tte_fu <- as.numeric(MCL_cox_pfs$tte_fu)
MCL_cox_pfs$stat_code <- as.numeric(MCL_cox_pfs$stat_code)

```

#Data preprocessing
```{r}
mclcox_recipe <- recipe(MCL_cox_pfs, stat_code ~ .) %>% 
  update_role(pt_id, new_role = "id variable") %>% 
  update_role (tte_fu, new_role = "follow up time") %>% 
  step_string2factor(all_string()) %>% 
  step_impute_knn(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_other(morph, threshold=.05) 

mcl_cox_prep <- prep(mclcox_recipe)

MCL_cox <- juice(mcl_cox_prep)

MCL_cox<-select(MCL_cox, -pt_id)

```

#Define the Cox model

```{r}
ph_spec <- 
  proportional_hazards() %>% 
  set_engine("survival") %>% 
  set_mode("censored regression")

ph_spec
```

#Create model fit object
```{r}
set.seed(102)

ph_fit <- ph_spec %>% fit(Surv(tte_fu, stat_code) ~., data=MCL_cox)

ph_fit


```
#run with regular survival package
```{r}
MCL_coxph<-coxph(formula=Surv(tte_fu, stat_code) ~., data=MCL_cox)
```

```{r}
summary(MCL_coxph)
```
#Make table
```{r}
library(gtsummary)

cox_ph_pfs <- MCL_coxph %>% 
  tbl_regression(exponentiate=TRUE, show_single_row=(c("b_symptoms","tp53","card11","birc3","notch1","ros1","gi_involve")))%>% 
  add_significance_stars() 
  
```

#Model for OS

```{r}
MCL_cox_os$tte_fu <- as.numeric(MCL_cox_os$tte_fu)
MCL_cox_os$stat_code_os <- as.numeric(MCL_cox_os$stat_code_os)



```

#Data preprocessing
```{r}
mclcox_recipe <- recipe(MCL_cox_os, stat_code_os ~ .) %>% 
  update_role(pt_id, new_role = "id variable") %>% 
  update_role (tte_fu, new_role = "follow up time") %>% 
  step_string2factor(all_string()) %>% 
  step_impute_knn(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_other(morph, threshold=.05) 

 

mcl_cox_prep <- prep(mclcox_recipe)

MCL_cox_dataset <- juice(mcl_cox_prep)

juice(mcl_cox_prep)
MCL_cox_dataset<-select(MCL_cox_dataset, -pt_id)

```
#Define the Cox model

```{r}
ph_spec <- 
  proportional_hazards() %>% 
  set_engine("survival") %>% 
  set_mode("censored regression")

ph_spec
```

#Create model fit object
```{r}
set.seed(102)

ph_fit <- ph_spec %>% fit(Surv(tte_fu, stat_code_os) ~., data=MCL_cox_dataset)

ph_fit

```
#run with regular survival package
```{r}
MCL_coxph<-coxph(formula=Surv(tte_fu, stat_code_os) ~., data=MCL_cox_dataset)



summary(MCL_coxph)

cox_ph_os <- MCL_coxph %>% 
  tbl_regression(exponentiate=TRUE,show_single_row=(c("b_symptoms","tp53","card11","birc3","notch1","ros1","gi_involve"))) %>% 
  add_significance_stars()

cox_ph_os
```

```{r}
library(gtsummary)

cox_ph_os <- MCL_coxph %>% 
  tbl_regression(exponentiate=TRUE, show_single_row=(c("b_symptoms","tp53","card11","birc3","notch1","ros1","gi_involve")))  %>% 
  add_significance_stars() 

cox_ph_os


```


#merge with OS table.
```{r}

tbl_merge_cox <- tbl_merge(
  tbls=list(cox_ph_pfs, cox_ph_os),
  tab_spanner = c("**Progression Free Survival**","**Overall Survival**")) %>% 
    as_gt() %>% 
  gt::tab_header(title="Table 4: Cox Regression Models") %>% 
  sub_values(values="morph", replacement = "Morphology") %>% 
  sub_values(values="ki_67", replacement = "Ki-67 %") %>% 
  sub_values(values="bm", replacement = "Bone Marrow Involvement")%>% 
  sub_values(values="ldh", replacement = "Lactate Dehydrogenase") %>%    
  sub_values(values="b2m", replacement = "Beta 2 Microglobulin") %>% 
  sub_values(values="wbc", replacement = "White Blood Cell Count") %>% 
  sub_values(values="hgb", replacement = "Hemoglobin") %>% 
  sub_values(values="platelets", replacement = "Platelets") %>% 
  sub_values(values="smoke", replacement = "Smoking Status") %>% 
  sub_values(values="ecog", replacement = "ECOG") %>% 
  sub_values(values="b_symptoms", replacement = "B Symptoms") %>% 
  sub_values(values="age_dx_years", replacement = "Age at Diagnosis") %>% 
  sub_values(values="bmi", replacement = "BMI") %>% 
  sub_values(values="tp53", replacement = "TP53 mutation") %>% 
  sub_values(values="card11", replacement = "CARD11 mutation") %>% 
  sub_values(values="total_genes_mutated", replacement = "Number of Somatic Mutations") %>% 
  sub_values(values="birc3", replacement = "BIRC3 mutation") %>% 
  sub_values(values="gi_involve", replacement = "GI Involvement") %>%
  sub_values(values="notch1", replacement = "NOTCH1 mutation") %>% 
  sub_values(values="ros1", replacement = "ROS1 mutation") %>% 
  opt_vertical_padding(scale=0.40)
  
  
               
                
                
  

tbl_merge_cox %>% 
  as_flex_table() %>% 
  flextable::save_as_docx(tbl_merge_cox, path="cox_models_2.docx")

```


